"""empty message

Revision ID: cd7d5ee047ab
Revises: 
Create Date: 2021-06-15 12:28:35.450207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7d5ee047ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('lgbtqia_plus', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traffics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('url_route', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traffics')
    op.drop_table('data')
    # ### end Alembic commands ###
